genres_by_id = {
    1: {'category': u'Basic Genres', 'name': u'Action'},
    2: {'category': u'Basic Genres', 'name': u'Adventure'},
    3: {'category': u'Basic Genres', 'name': u'Simulation'},
    4: {'category': u'Basic Genres', 'name': u'Strategy/Tactics'},
    5: {'category': u'Basic Genres', 'name': u'Sports'},
    6: {'category': u'Basic Genres', 'name': u'Racing / Driving'},
    7: {'category': u'Perspective', 'name': u'1st-person'},
    8: {'category': u'Setting', 'name': u'Sci-Fi / Futuristic'},
    9: {'category': u'Gameplay', 'name': u'Arcade'},
    11: {'category': u'Gameplay', 'name': u'Chess'},
    12: {'category': u'Basic Genres', 'name': u'Educational'},
    13: {'category': u'Perspective', 'name': u'Top-down'},
    14: {'category': u'Setting', 'name': u'Historical Events'},
    15: {'category': u'Pacing', 'name': u'Real-Time'},
    16: {'category': u'Perspective', 'name': u'3rd-person [DEPRECATED]'},
    17: {'category': u'Perspective', 'name': u'Side view'},
    18: {'category': u'Sports Themes', 'name': u'Fishing'},
    19: {'category': u'Vehicular Themes', 'name': u'Flight / Aviation'},
    20: {'category': u'Vehicular Themes', 'name': u'Motorcycle'},
    21: {'category': u'Gameplay', 'name': u'Platform'},
    22: {'category': u'Gameplay', 'name': u'Shooter'},
    23: {'category': u'Gameplay', 'name': u'Interactive Fiction / Text Adventure'},
    24: {'category': u'Gameplay', 'name': u'Metroidvania'},
    25: {'category': u'Visual Presentation', 'name': u'Isometric'},
    26: {'category': u'Gameplay', 'name': u'Board Game'},
    27: {'category': u'Gameplay', 'name': u'Cards / Tiles'},
    28: {'category': u'Gameplay', 'name': u'Casino'},
    29: {'category': u'Gameplay', 'name': u'Game Show / Trivia / Quiz'},
    30: {'category': u'Gameplay', 'name': u'Puzzle-solving'},
    31: {'category': u'Sports Themes', 'name': u'Football (American)'},
    32: {'category': u'Sports Themes', 'name': u'Baseball'},
    33: {'category': u'Sports Themes', 'name': u'Basketball'},
    34: {'category': u'Sports Themes', 'name': u'Hockey'},
    35: {'category': u'Sports Themes', 'name': u'Golf'},
    36: {'category': u'Sports Themes', 'name': u'Boxing'},
    37: {'category': u'Sports Themes', 'name': u'Tennis'},
    38: {'category': u'Sports Themes', 'name': u'Olympiad / Mixed Sports'},
    39: {'category': u'Gameplay', 'name': u'Martial Arts'},
    40: {'category': u'Gameplay', 'name': u'Managerial / Business Simulation'},
    41: {'category': u'Vehicular Themes', 'name': u'Naval / Watercraft'},
    43: {'category': u'Educational Categories', 'name': u'Math / Logic'},
    44: {'category': u'Educational Categories', 'name': u'Reading / Writing'},
    45: {'category': u'Educational Categories', 'name': u'Typing'},
    46: {'category': u'Educational Categories', 'name': u'Pre-school / Toddler'},
    48: {'category': u'Gameplay', 'name': u'Fighting'},
    49: {'category': u'Sports Themes', 'name': u'Football (European) / Soccer'},
    50: {'category': u'Basic Genres', 'name': u'Role-Playing (RPG)'},
    51: {'category': u'Sports Themes', 'name': u'Wrestling'},
    52: {'category': u'Sports Themes', 'name': u'Skateboarding'},
    53: {'category': u'Gameplay', 'name': u'Pinball'},
    55: {'category': u'Narrative Theme/Topic', 'name': u'Detective / Mystery'},
    56: {'category': u'Vehicular Themes', 'name': u'Helicopter'},
    57: {'category': u'Art Style', 'name': u'Anime / Manga'},
    58: {'category': u'Vehicular Themes', 'name': u'Off-roading'},
    59: {'category': u'Educational Categories', 'name': u'Music'},
    60: {'category': u'Art Style', 'name': u'Full Motion Video (FMV)'},
    61: {'category': u'Gameplay', 'name': u'Hunting'},
    62: {'category': u'Basic Genres', 'name': u'DLC / Add-on'},
    63: {'category': u'Sports Themes', 'name': u'Sailing / Boating'},
    64: {'category': u'Gameplay', 'name': u'Paddle / Pong'},
    65: {'category': u'Setting', 'name': u'Post-Apocalyptic'},
    66: {'category': u'Setting', 'name': u'Cyberpunk / Dark Sci-Fi'},
    67: {'category': u'Art Style', 'name': u'Video backdrop'},
    68: {'category': u'Gameplay', 'name': u'Hack and Slash'},
    69: {'category': u'Pacing', 'name': u'Meditative / Zen'},
    71: {'category': u'Educational Categories', 'name': u'Geography'},
    72: {'category': u'Vehicular Themes', 'name': u'Mecha / Giant Robot'},
    73: {'category': u'Sports Themes', 'name': u'Cricket'},
    74: {'category': u'Educational Categories', 'name': u'History'},
    75: {'category': u'Sports Themes', 'name': u'Rugby'},
    76: {'category': u'Basic Genres', 'name': u'Compilation'},
    77: {'category': u'Sports Themes', 'name': u'Volleyball'},
    78: {'category': u'Setting', 'name': u'Fantasy'},
    79: {'category': u'Educational Categories', 'name': u'Graphics / Art'},
    80: {'category': u'Vehicular Themes', 'name': u'Tank'},
    81: {'category': u'Educational Categories', 'name': u'Ecology / Nature'},
    82: {'category': u'Other Attributes', 'name': u'Licensed'},
    83: {'category': u'Narrative Theme/Topic', 'name': u'Horror'},
    84: {'category': u'Educational Categories', 'name': u'Religion'},
    85: {'category': u'Educational Categories', 'name': u'Foreign Language'},
    86: {'category': u'Educational Categories', 'name': u'Science'},
    87: {'category': u'Narrative Theme/Topic', 'name': u'Adult'},
    88: {'category': u'Sports Themes', 'name': u'Bowling'},
    89: {'category': u'Sports Themes', 'name': u'Pool / Snooker'},
    91: {'category': u'Sports Themes', 'name': u'Horse / Derby'},
    92: {'category': u'Educational Categories', 'name': u'Health / Nutrition'},
    93: {'category': u'Narrative Theme/Topic', 'name': u'Spy / Espionage'},
    94: {'category': u'Pacing', 'name': u'Persistent'},
    95: {'category': u'Sports Themes', 'name': u'Snowboarding / Skiing'},
    96: {'category': u'Gameplay', 'name': u'Tricks / Stunts'},
    97: {'category': u'Gameplay', 'name': u'Music / Rhythm'},
    98: {'category': u'Educational Categories', 'name': u'Sociology'},
    99: {'category': u'Gameplay', 'name': u'Stealth'},
    102: {'category': u'Gameplay', 'name': u'Survival Horror'},
    103: {'category': u'Sports Themes', 'name': u'Ping Pong / Table Tennis'},
    104: {'category': u'Vehicular Themes', 'name': u'Bike / Bicycling'},
    105: {'category': u'Sports Themes', 'name': u'Paintball'},
    106: {'category': u'Pacing', 'name': u'Turn-based'},
    107: {'category': u'Gameplay', 'name': u'Mental training'},
    108: {'category': u'Vehicular Themes', 'name': u'Train'},
    109: {'category': u'Sports Themes', 'name': u'Surfing'},
    110: {'category': u'Sports Themes', 'name': u'Wakeboarding'},
    111: {'category': u'Gameplay', 'name': u'Visual Novel'},
    116: {'category': u'Gameplay', 'name': u'Hidden object'},
    117: {'category': u'Gameplay', 'name': u"Beat 'em up / Brawler"},
    118: {'category': u'Basic Genres', 'name': u'Puzzle'},
    119: {'category': u'Sports Themes', 'name': u'Darts / Target Shooting'},
    120: {'category': u'Narrative Theme/Topic', 'name': u'Comedy'},
    121: {'category': u'Narrative Theme/Topic', 'name': u'Crime'},
    122: {'category': u'Narrative Theme/Topic', 'name': u'Romance'},
    123: {'category': u'Narrative Theme/Topic', 'name': u'Thriller'},
    124: {'category': u'Narrative Theme/Topic', 'name': u'War'},
    125: {'category': u'Sports Themes', 'name': u'Dodgeball'},
    126: {'category': u'Perspective', 'name': u'3rd-person'},
    127: {'category': u'Perspective', 'name': u'Audio game'},
    128: {'category': u'Perspective', 'name': u'Behind view'},
    129: {'category': u'Perspective', 'name': u"Bird's-eye view"},
    130: {'category': u'Perspective', 'name': u'Text-based / Spreadsheet'},
    131: {'category': u'Visual Presentation', 'name': u'2D scrolling'},
    132: {'category': u'Visual Presentation', 'name': u'Cinematic camera'},
    133: {'category': u'Visual Presentation', 'name': u'Fixed / Flip-screen'},
    134: {'category': u'Visual Presentation', 'name': u'Free-roaming camera'},
    135: {'category': u'Sports Themes', 'name': u'Athletics'},
    136: {'category': u'Sports Themes', 'name': u'Racquetball / Squash'},
    137: {'category': u'Gameplay', 'name': u'City Building / Construction Simulation'},
    138: {'category': u'Gameplay', 'name': u'Dating Simulation'},
    139: {'category': u'Gameplay', 'name': u'Life / Social Simulation'},
    140: {'category': u'Gameplay', 'name': u'Mini-Games'},
    141: {'category': u'Narrative Theme/Topic', 'name': u'Healthcare'},
    142: {'category': u'Gameplay', 'name': u'4X'},
    143: {'category': u'Gameplay', 'name': u'Artillery'},
    144: {'category': u'Gameplay', 'name': u'Party Game'},
    145: {'category': u'Gameplay', 'name': u'Falling Block Puzzle'},
    146: {'category': u'Gameplay', 'name': u'Graphic Adventure'},
    147: {'category': u'Gameplay', 'name': u'Japanese-style RPG (JRPG)'},
    148: {'category': u'Gameplay', 'name': u'Rail Shooter'},
    149: {'category': u'Gameplay', 'name': u'Roguelike'},
    150: {'category': u'Gameplay', 'name': u'Sandbox / Open World'},
    151: {'category': u'Vehicular Themes', 'name': u'Space Flight'},
    152: {'category': u'Gameplay', 'name': u'Tactical RPG'},
    153: {'category': u'Gameplay', 'name': u'Tactical Shooter'},
    154: {'category': u'Gameplay', 'name': u'Tile Matching Puzzle'},
    155: {'category': u'Gameplay', 'name': u'Time Management'},
    156: {'category': u'Gameplay', 'name': u'Tower Defense'},
    157: {'category': u'Gameplay', 'name': u'Trading / Collectible Card'},
    158: {'category': u'Gameplay', 'name': u'Vehicle Simulator'},
    159: {'category': u'Gameplay', 'name': u'Vehicular Combat Simulator'},
    160: {'category': u'Gameplay', 'name': u'Virtual World'},
    161: {'category': u'Gameplay', 'name': u'Wargame'},
    162: {'category': u'Gameplay', 'name': u'Word Construction'},
    163: {'category': u'Narrative Theme/Topic', 'name': u'Survival'},
    164: {'category': u'Gameplay', 'name': u'Japanese-style Adventure'},
    165: {'category': u'Gameplay', 'name': u'RPG Elements'},
    166: {'category': u'Gameplay', 'name': u'Action RPG'},
    167: {'category': u'Interface/Control', 'name': u'Point and Select'},
    168: {'category': u'Interface/Control', 'name': u'Direct Control'},
    169: {'category': u'Interface/Control', 'name': u'Motion Control'},
    170: {'category': u'Interface/Control', 'name': u'Voice Control'},
    171: {'category': u'Interface/Control', 'name': u'Text Parser'},
    172: {'category': u'Interface/Control', 'name': u'Menu Structures'},
    173: {'category': u'Interface/Control', 'name': u'Multiple Units/Characters Control'},
    174: {'category': u'DLC/Add-on', 'name': u'Currency'},
    175: {'category': u'DLC/Add-on', 'name': u'Enemy'},
    176: {'category': u'DLC/Add-on', 'name': u'Extras'},
    177: {'category': u'DLC/Add-on', 'name': u'Game Mode'},
    178: {'category': u'DLC/Add-on', 'name': u'Item'},
    179: {'category': u'DLC/Add-on', 'name': u'Map / Level'},
    180: {'category': u'DLC/Add-on', 'name': u'Other'},
    181: {'category': u'DLC/Add-on', 'name': u'Customization / Outfit / Skin'},
    182: {'category': u'DLC/Add-on', 'name': u'Player Unit'},
    183: {'category': u'DLC/Add-on', 'name': u'Story / Mission'},
    184: {'category': u'Special Edition', 'name': u'Digital Extras'},
    185: {'category': u'Special Edition', 'name': u'Extra Content/Game'},
    186: {'category': u'Special Edition', 'name': u'Physical Extras'},
    187: {'category': u'Basic Genres', 'name': u'Special Edition'},
    188: {'category': u'Vehicular Themes', 'name': u'Automobile'},
    189: {'category': u'Vehicular Themes', 'name': u'Hovercraft'},
    190: {'category': u'Setting', 'name': u'Prehistoric'},
    191: {'category': u'Vehicular Themes', 'name': u'Street Racing'},
    192: {'category': u'Vehicular Themes', 'name': u'Track Racing'},
    193: {'category': u'Vehicular Themes', 'name': u'Transport'},
    194: {'category': u'Vehicular Themes', 'name': u'Truck'},
    195: {'category': u'Gameplay', 'name': u'Interactive Book'},
    196: {'category': u'Setting', 'name': u'Africa'},
    197: {'category': u'Setting', 'name': u'Asia'},
    198: {'category': u'Setting', 'name': u'China (Ancient/Imperial)'},
    199: {'category': u'Setting', 'name': u'Cold War'},
    200: {'category': u'Setting', 'name': u'Contemporary'},
    201: {'category': u'Setting', 'name': u'Egypt (Ancient)'},
    202: {'category': u'Setting', 'name': u'Europe'},
    203: {'category': u'Setting', 'name': u'Classical antiquity'},
    204: {'category': u'Setting', 'name': u'Industrial Age'},
    205: {'category': u'Setting', 'name': u'Medieval'},
    206: {'category': u'Setting', 'name': u'Middle East'},
    207: {'category': u'Setting', 'name': u'North America'},
    208: {'category': u'Setting', 'name': u'Oceania'},
    209: {'category': u'Setting', 'name': u'Pre-Columbian Americas'},
    210: {'category': u'Setting', 'name': u'Sea Pirates/Caribbean'},
    211: {'category': u'Setting', 'name': u'South America'},
    212: {'category': u'Setting', 'name': u'Steampunk'},
    213: {'category': u'Setting', 'name': u'Western'},
    214: {'category': u'Setting', 'name': u'World War I'},
    215: {'category': u'Setting', 'name': u'World War II'},
    216: {'category': u'Setting', 'name': u'Interwar'},
    217: {'category': u'Art Style', 'name': u'Live action'},
    218: {'category': u'Gameplay', 'name': u'Timed Input'},
    219: {'category': u'Gameplay', 'name': u'Quick Time Events (QTEs)'},
    220: {'category': u'Setting', 'name': u'Japan (Ancient/Classical/Medieval)'}
}

platforms_by_id = {
    1: u'Linux',
    2: u'DOS',
    3: u'Windows',
    4: u'PC Booter',
    5: u'Windows 3.x',
    6: u'PlayStation',
    7: u'PlayStation 2',
    8: u'Dreamcast',
    9: u'Nintendo 64',
    10: u'Game Boy',
    11: u'Game Boy Color',
    12: u'Game Boy Advance',
    13: u'Xbox',
    14: u'GameCube',
    15: u'SNES',
    16: u'Genesis',
    17: u'Jaguar',
    18: u'Lynx',
    19: u'Amiga',
    20: u'SEGA CD',
    21: u'SEGA 32X',
    22: u'NES',
    23: u'SEGA Saturn',
    24: u'Atari ST',
    25: u'Game Gear',
    26: u'SEGA Master System',
    27: u'Commodore 64',
    28: u'Atari 2600',
    29: u'ColecoVision',
    30: u'Intellivision',
    31: u'Apple II',
    32: u'N-Gage',
    33: u'Atari 5200',
    34: u'Atari 7800',
    35: u'3DO',
    36: u'Neo Geo',
    37: u'Vectrex',
    38: u'Virtual Boy',
    39: u'Atari 8-bit',
    40: u'TurboGrafx-16',
    41: u'ZX Spectrum',
    42: u'V.Smile',
    43: u'VIC-20',
    44: u'Nintendo DS',
    45: u'TurboGrafx CD',
    46: u'PSP',
    47: u'TI-99/4A',
    48: u'WonderSwan',
    49: u'WonderSwan Color',
    50: u'Game.Com',
    51: u'Apple IIgs',
    52: u'Neo Geo Pocket',
    53: u'Neo Geo Pocket Color',
    54: u'Neo Geo CD',
    55: u'Gizmondo',
    56: u'Amiga CD32',
    57: u'MSX',
    58: u'TRS-80',
    59: u'PC-FX',
    60: u'Amstrad CPC',
    61: u'Commodore 128',
    62: u'TRS-80 CoCo',
    63: u'BREW',
    64: u'J2ME',
    65: u'Palm OS',
    66: u'Windows Mobile',
    67: u'Symbian',
    68: u'Zodiac',
    69: u'Xbox 360',
    70: u'ExEn',
    71: u'Mophun',
    72: u'DoJa',
    73: u'CD-i',
    74: u'Macintosh',
    75: u'Odyssey',
    76: u'Channel F',
    77: u'Commodore PET/CBM',
    78: u'Odyssey 2',
    79: u'Dragon 32/64',
    80: u'iPod Classic',
    81: u'PlayStation 3',
    82: u'Wii',
    83: u'CDTV',
    84: u'Browser',
    85: u'Spectravideo',
    86: u'iPhone',
    87: u'Nintendo DSi',
    88: u'Zeebo',
    89: u'N-Gage (service)',
    90: u'BlackBerry',
    91: u'Android',
    92: u'BBC Micro',
    93: u'Electron',
    94: u'PC-88',
    95: u'PC-98',
    96: u'iPad',
    97: u'Microvision',
    98: u'Windows Phone',
    99: u'bada',
    100: u'webOS',
    101: u'Nintendo 3DS',
    102: u'FM Towns',
    103: u'SEGA Pico',
    104: u'Game Wave',
    105: u'PS Vita',
    106: u'Sharp X68000',
    107: u'Playdia',
    108: u'GP32',
    109: u'Supervision',
    110: u"Super A'can",
    111: u'Oric',
    112: u'Pippin',
    113: u'RCA Studio II',
    114: u'SG-1000',
    115: u'Commodore 16, Plus/4',
    116: u'Nuon',
    117: u'Acorn 32-bit',
    118: u'ZX80',
    119: u'ZX81',
    120: u'SAM Coup\xe9',
    121: u'Sharp X1',
    122: u'GP2X',
    123: u'GP2X Wiz',
    124: u'Casio Loopy',
    125: u'Casio PV-1000',
    126: u'FM-7',
    127: u'SuperGrafx',
    128: u'Videopac+ G7400',
    129: u'Atom',
    130: u'Thomson TO',
    131: u'Sinclair QL',
    132: u'Wii U',
    133: u'Philips VG 5000',
    134: u'Sord M5',
    135: u'Mattel Aquarius',
    136: u'Amstrad PCW',
    137: u'Epoch Cassette Vision',
    138: u'Epoch Super Cassette Vision',
    139: u'Epoch Game Pocket Computer',
    140: u'Windows Apps',
    141: u'PlayStation 4',
    142: u'Xbox One',
    143: u'Arcade',
    144: u'Ouya',
    145: u'Kindle Classic',
    146: u'OS/2',
    147: u'Thomson MO',
    148: u'Memotech MTX',
    149: u'PC-6001',
    150: u'Tatung Einstein',
    151: u'Tomy Tutor',
    152: u'Pok\xe9mon Mini',
    153: u'Jupiter Ace',
    154: u'Camputers Lynx',
    155: u'GameStick',
    156: u'Coleco Adam',
    157: u'Maemo',
    158: u'MeeGo',
    159: u'Fire OS',
    160: u'Bally Astrocade',
    161: u'Enterprise',
    162: u'Arcadia 2001',
    163: u'LaserActive',
    164: u'VIS',
    165: u'BeOS',
    166: u'DVD Player',
    167: u'HD DVD Player',
    168: u'Blu-ray Disc Player',
    169: u'Z-machine',
    170: u'Hugo',
    171: u'TADS',
    172: u'Glulx',
    173: u'Timex Sinclair 2068',
    174: u'New Nintendo 3DS',
    175: u'Nascom',
    176: u'Exidy Sorcerer',
    177: u'NewBrain',
    178: u'Ohio Scientific',
    179: u'tvOS',
    180: u'watchOS',
    181: u'Sharp MZ-80K/700/800/1500',
    182: u'Sharp MZ-80B/2000/2500',
    183: u'Leapster',
    184: u'Didj',
    185: u'LeapFrog Explorer',
    186: u'LeapTV',
    187: u'digiBlast',
    188: u'ClickStart',
    189: u'V.Flash',
    190: u'Socrates',
    191: u'XaviXPORT',
    192: u'HyperScan',
    193: u'TRS-80 MC-10',
    194: u'Alice 32/90',
    195: u'Exelvision',
    196: u'Roku',
    197: u'Colour Genie',
    198: u'Compucolor II',
    199: u'Sol-20',
    200: u'Microbee',
    201: u'PC-8000',
    202: u'Sharp Zaurus',
    203: u'Nintendo Switch',
    204: u'Dedicated console',
    205: u'Dedicated handheld',
    206: u'Tizen',
    207: u'Newton',
    208: u'Mainframe',
    209: u'Terminal',
    210: u'Adventure Vision',
    211: u'Zune',
    212: u'CreatiVision',
    213: u'APF MP1000/Imagination Machine',
    214: u'VideoBrain'
}
